services:
  whisper-asr-webservice:
    container_name: whisper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASR_MODEL=small
      - ASR_ENGINE=faster_whisper
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./whisper/cache-pip:/root/.cache/pip
      - ./whisper/cache-poetry:/root/.cache/poetry
      - ./whisper/cache-whisper:/root/.cache/whisper
      
